SE01-TeamProject/TTS08

src/main/java/com/example/demo/Comment.java
src/main/java/com/example/demo/Issue.java
src/main/java/com/example/demo/IssueManager.java
src/main/java/com/example/demo/Project.java
src/main/java/com/example/demo/Recommender.java
src/main/java/com/example/demo/System.java
src/main/java/com/example/demo/user/Admin.java
src/main/java/com/example/demo/user/Developer.java
src/main/java/com/example/demo/user/PL.java
src/main/java/com/example/demo/user/Tester.java
src/main/java/com/example/demo/user/User.java

클래스 다이어그램을 기반으로 기초 클래스를 추가했습니다.
아직 자세한 내용은 없습니다.

Added class based on diagrams

---

src/main/resources/static/admin.html
src/main/resources/static/adminstyle.css
src/main/resources/static/home.html
src/main/resources/static/index.html
src/main/resources/static/login.html
src/main/resources/static/ticketpage.html
src/main/resources/static/ticketstyle.css

login, ticketpage, home, admin html

WebUI add html files.

---

src/ui/LoginWindow.java
src/ui/MainWindow.java
src/ui/ProjectPanel.java
src/ui/Test.java
src/ui/TicketPanel.java
src/ui/TimelinePanel.java

Swing UI Created

---

src/main/resources/static/admin.html
src/main/resources/static/adminstyle.css
src/main/resources/static/ticketstyle.css

admin 페이지 frame을 완성했습니다 (아직 api 관련 js 함수는 안짰음)

update: admin complete

---

src/main/resources/static/admin.html
src/main/resources/static/adminstyle.css
src/main/resources/static/globalScript.js
src/main/resources/static/globalstyle.css
src/main/resources/static/home.html
src/main/resources/static/homestyle.css
src/main/resources/static/login.css
src/main/resources/static/login.html
src/main/resources/static/ticketpage.html

전체적인 페이지의 구성을 중심에 오도록 변경, 홈페이지로 이동 link 완료, css 및 js 완전 분리 및 각각 global 파일 생성

update: refactored all pages, css&js file seperation

---

src/main/java/com/example/demo/domain/Admin.java
src/main/java/com/example/demo/domain/Comment.java
src/main/java/com/example/demo/domain/Developer.java
src/main/java/com/example/demo/domain/Issue.java
src/main/java/com/example/demo/domain/PL.java
src/main/java/com/example/demo/domain/Project.java
src/main/java/com/example/demo/domain/Tester.java
src/main/java/com/example/demo/domain/User.java
src/main/java/com/example/demo/service/IssueManager.java
src/main/java/com/example/demo/service/Recommender.java
src/main/java/com/example/demo/service/System.java

클래스들에 annotation과 method를 넣었습니다
아직 method의 세부 코드는 작성하지 않았습니다

edited classes for backend service

---

src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/controller/ProjectController.java
src/main/java/com/example/demo/domain/Issue.java
src/main/java/com/example/demo/dto/IssueAddDto.java
src/main/java/com/example/demo/service/IssueService.java
src/main/java/com/example/demo/service/ProjectService.java
src/main/resources/static/issue.html

Issue 페이지의 Add Issue 기능 구현했습니다
추후 Issue는 Reporter, Assignee, Priority, Status, Type을 추가로 받아야 합니다.

add issue added

---

src/main/resources/static/issue.html

issue 쪽이라 나중에 conflict 크게 날까봐 미리 merge

update : some js function (local storage)

---

src/main/resources/static/issue.html

웹에 독립적으로 존재하는 Storage인 localStorage를 이용하여 로그인한 유저의 id를 저장하였고, comment 작성자를 바로 넣어지도록 설정하엿음

update: use localStorage in Writer Id

---

build.gradle
src/main/java/com/example/demo/dto/ProjectAddDto.java
src/test/java/com/example/demo/controller/ProjectControllerTest.java

add: ProjectControllerTest success case

---

src/main/java/com/example/demo/controller/CommentController.java
src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/controller/MemberController.java
src/main/java/com/example/demo/controller/ProjectController.java
src/main/java/com/example/demo/domain/Comment.java
src/main/java/com/example/demo/domain/Issue.java
src/main/java/com/example/demo/domain/Log.java
src/main/java/com/example/demo/domain/Member.java
src/main/java/com/example/demo/domain/Project.java
src/main/java/com/example/demo/dto/CommentAddDto.java
src/main/java/com/example/demo/repository/IssueRepository.java
src/main/java/com/example/demo/repository/ProjectRepository.java
src/main/java/com/example/demo/service/CommentService.java
src/main/java/com/example/demo/service/IssueService.java
src/main/java/com/example/demo/service/MemberService.java
src/main/java/com/example/demo/service/ProjectService.java
src/main/java/com/example/demo/ui/SwingController.java
src/main/java/com/example/demo/ui/TimelinePanel.java
src/test/java/com/example/demo/controller/ProjectControllerTest.java

만든 것
- addComment: 코멘트 생성 (/addComment)
- Member/Project/Issue/Comment에서 고유 id를 주고 정보를 받는 메소드 
접근방법: (/user/{id}) 또는 (/user/1)
- Issue에서 Project의 고유 id를 주고 해당 이슈들을 받는 메소드 
접근방법: (/listIssue/{id}) 또는 (/listIssue/1)
- Comment에서 Issue의 고유 id를 주고 해당 코멘트들을 받는 메소드
접근방법: (/listComment/{id}) 또는 (/listComment/1)

added various methods

---

src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/dto/IssueSetDto.java
src/main/java/com/example/demo/service/IssueService.java

이슈에서 assignee 교체하는 기능 추가했습니다 - 검증되지는 않았습니다

added assignee set for issue

---

src/main/java/com/example/demo/domain/Issue.java
src/main/java/com/example/demo/dto/IssueAddDto.java
src/main/java/com/example/demo/service/IssueService.java
src/main/java/com/example/demo/service/ProjectService.java

이슈 추가 기능이 이제 reporter, priority, type을 입력으로 받습니다

addIssue now gets reporter, priority, type as input

---

src/main/java/com/example/demo/Tts08Application.java
src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/repository/IssueRepository.java
src/main/java/com/example/demo/service/IssueService.java
src/main/resources/application.yml

이슈 트렌드 기능의 Priority/Status/Type 갯수 세기 메소드를 추가했습니다
테스트를 위해 main의 예시 이슈들도 잠시 되살려놓았습니다
DB 충돌이 있을 수 있기 때문에 test.mv.db를 삭제해서 초기화하거나 application.yml의 ddl-auto를 잠시 create로 전환해서 테스트하세요
URL은 http://localhost:8080/issueTrend

added Issue trend making method

---

src/test/java/com/example/demo/service/MemberServiceTest.java

MemberServiceTest add

---

build.gradle
src/main/java/com/example/demo/config/SwaggerConfig.java

http://localhost:8080/swagger-ui/index.html#/

Swagger add

---

src/main/java/com/example/demo/service/IssueService.java

이슈 통계 기능으로 해당 월에 생성된 이슈 갯수 세기 메소드를 추가했습니다
URL은 http://localhost:8080/issueStatics

added Issue statics making method

---

src/main/java/com/example/demo/controller/MemberController.java
src/main/java/com/example/demo/service/IssueService.java
src/main/java/com/example/demo/service/MemberService.java

added member search with name

---

src/main/java/com/example/demo/Tts08Application.java
src/main/resources/application.yml
src/test/java/com/example/demo/controller/CommentControllerTest.java

fix: controller test

---

src/main/resources/static/admin.html
src/main/resources/static/adminstyle.css
src/main/resources/static/globalScript.js
src/main/resources/static/issueupdate.html
src/main/resources/static/issueupdateScript.js
src/main/resources/static/issueupdatestyle.css
src/main/resources/static/loginScript.js

update : comments complete

---

src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/difflib/SequenceMatcher.java
src/main/java/com/example/demo/dto/IssueSetDto.java
src/main/java/com/example/demo/service/IssueService.java

- description을 다른 이슈들의 description/comment들과 내용을 비교해서 유사도 측정 후 해당 이슈들에 배정된 assignee들 탐색
- 이슈 작성 시 description을 작성 후 추천 버튼 누르면
- 가장 추천도가 높은 {"assignee: x", "score: x"}를 반환
- UI상으로는 추천 버튼을 누르면 assignee 이름을 [추천] 이라는 글자 옆에 띄우면 될 듯

added recommend method

---

src/main/java/com/example/demo/controller/IssueController.java
src/main/java/com/example/demo/service/IssueService.java
src/main/resources/static/issueupdate.html
src/main/resources/static/issueupdateScript.js
src/main/resources/static/issueupdatestyle.css

setIssue api Swing에서 PATCH가 안되는 관계로 POST로 변경, 
recommend 기능은 넣긴 했으나 아직 테스트 안했음

fix: setIssue api PATCH->POST, add: recommend Assignee webFE
